name: flutter_paystack_payment
description: A plugin for Payment through Paystack
version: 0.1.2+3
homepage: https://github.com/DEVSOG12/flutter_paystack_payment

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.18.0
  meta: ^1.7.0
  async: ^2.8.2
  # Required for Dart Encryption
  basic_utils: ^5.7.0
  pointycastle: ^3.6.0

  # For Requests for Device
  platform_info: ^3.2.0
  device_info_plus: ^9.0.1

  # webview_flutter_web: ^0.1.0+1
  package_info_plus: ^4.0.0
  webview_flutter: ^4.0.6
  universal_html: ^2.2.2
  csslib: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  matcher: ^0.12.11
  mockito: ^5.2.0

flutter:
  assets:
    - assets/images/
  plugin:
    platforms:
      android:
        default_package: flutter_paystack_payment
      linux:
        default_package: flutter_paystack_payment
      windows:
        default_package: flutter_paystack_payment
      ios:
        default_package: flutter_paystack_payment
      web:
        default_package: flutter_paystack_payment
